# Credits
https://www.youtube.com/watch?v=rPFkX5fJdRY&t=1179s

## Positional encoding

In [1]:
import torch
import torch.nn as nn

In [2]:
#first we need to define the max input senquence(usually thousands) and the d_model(the size of the embadding layer)
max_sequence_length = 10
d_model = 6

### Formula of the postinal encoding
Same as the papaer

$$
PE_{(pos , 2i)} = \sin({\frac{pos}{10000^{2i/d_{model}}}}) 
$$


$$
PE_{(pos , 2i+1)} = \cos({\frac{pos}{10000^{2i/d_{model}}}})
$$


we can rewrite it as follows


$$
PE_{(pos , i)} = sin({\frac{pos}{10000^{i/d_{model}}}}) 
$$

$$PE_{(pos , 1)} = \cos({\frac{pos}{10000^{i-1/d_{model}}}})
$$


In [19]:
# Let evaluate only de demominator for the even and odd number
even_array = torch.arange(0, d_model, 2).float()
odd_array = torch.arange(1, d_model, 2).float()

even_denominator = torch.pow(10E3, even_array/d_model)
print(f'even_denominator: {even_denominator}')

odd_denominator = torch.pow(10E3, (odd_array-1)/d_model)
print(f'odd_denominator: {odd_denominator}')

even_denominator: tensor([  1.0000,  21.5443, 464.1590])
odd_denominator: tensor([  1.0000,  21.5443, 464.1590])


In [23]:
#since the values are the same we can use only one denominator
denominator  = odd_denominator
#now let's create our positional vector
positional = torch.arange(max_sequence_length, dtype=torch.float).reshape(max_sequence_length,1)
print(f'Positional:\n {positional}')

Positional:
 tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])


In [24]:
#now lest compute the even and odd positional embeddings
even_PE = torch.sin(positional/denominator)
odd_PE = torch.cos(positional/denominator)

print(f'even_PE:\n {even_PE}')

print(f'odd_PE:\n {odd_PE}')

even_PE:
 tensor([[ 0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.0464,  0.0022],
        [ 0.9093,  0.0927,  0.0043],
        [ 0.1411,  0.1388,  0.0065],
        [-0.7568,  0.1846,  0.0086],
        [-0.9589,  0.2300,  0.0108],
        [-0.2794,  0.2749,  0.0129],
        [ 0.6570,  0.3192,  0.0151],
        [ 0.9894,  0.3629,  0.0172],
        [ 0.4121,  0.4057,  0.0194]])
odd_PE:
 tensor([[ 1.0000,  1.0000,  1.0000],
        [ 0.5403,  0.9989,  1.0000],
        [-0.4161,  0.9957,  1.0000],
        [-0.9900,  0.9903,  1.0000],
        [-0.6536,  0.9828,  1.0000],
        [ 0.2837,  0.9732,  0.9999],
        [ 0.9602,  0.9615,  0.9999],
        [ 0.7539,  0.9477,  0.9999],
        [-0.1455,  0.9318,  0.9999],
        [-0.9111,  0.9140,  0.9998]])


In [ ]:
#now we need to reorder them
stacked = torch.stack([even_PE, odd_PE], dim=2)
